name: desktop-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Depedencies
              run: make install

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Build
              run: make build
